# Form implementation generated from reading ui file '.\sample\sample_main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SampleMain(object):
    def setupUi(self, SampleMain):
        SampleMain.setObjectName("SampleMain")
        SampleMain.resize(1001, 508)
        SampleMain.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(parent=SampleMain)
        self.centralwidget.setObjectName("centralwidget")
        self.grpTable = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.grpTable.setGeometry(QtCore.QRect(10, 10, 641, 471))
        self.grpTable.setTitle("")
        self.grpTable.setObjectName("grpTable")
        self.btnAddRow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddRow.setGeometry(QtCore.QRect(860, 10, 121, 31))
        self.btnAddRow.setObjectName("btnAddRow")
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(860, 50, 121, 31))
        self.btnDelete.setObjectName("btnDelete")
        self.btnMoveUp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMoveUp.setGeometry(QtCore.QRect(860, 90, 121, 31))
        self.btnMoveUp.setObjectName("btnMoveUp")
        self.btnMoveDown = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnMoveDown.setGeometry(QtCore.QRect(860, 130, 121, 31))
        self.btnMoveDown.setObjectName("btnMoveDown")
        SampleMain.setCentralWidget(self.centralwidget)
        self.actionSave = QtGui.QAction(parent=SampleMain)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(parent=SampleMain)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtGui.QAction(parent=SampleMain)
        self.actionExit.setObjectName("actionExit")
        self.actionClear = QtGui.QAction(parent=SampleMain)
        self.actionClear.setObjectName("actionClear")
        self.actionSaveAs = QtGui.QAction(parent=SampleMain)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionSaveAs1 = QtGui.QAction(parent=SampleMain)
        self.actionSaveAs1.setObjectName("actionSaveAs1")
        self.actionNew = QtGui.QAction(parent=SampleMain)
        self.actionNew.setObjectName("actionNew")
        self.actionSkill_Tool = QtGui.QAction(parent=SampleMain)
        self.actionSkill_Tool.setObjectName("actionSkill_Tool")

        self.retranslateUi(SampleMain)
        QtCore.QMetaObject.connectSlotsByName(SampleMain)

    def retranslateUi(self, SampleMain):
        _translate = QtCore.QCoreApplication.translate
        SampleMain.setWindowTitle(_translate("SampleMain", "Ran Auto"))
        self.btnAddRow.setText(_translate("SampleMain", "Add Row"))
        self.btnDelete.setText(_translate("SampleMain", "Delete"))
        self.btnMoveUp.setText(_translate("SampleMain", "Move Up"))
        self.btnMoveDown.setText(_translate("SampleMain", "Move Down"))
        self.actionSave.setText(_translate("SampleMain", "Save"))
        self.actionSave.setShortcut(_translate("SampleMain", "Ctrl+S"))
        self.actionLoad.setText(_translate("SampleMain", "Load"))
        self.actionLoad.setShortcut(_translate("SampleMain", "Ctrl+O"))
        self.actionExit.setText(_translate("SampleMain", "Exit"))
        self.actionClear.setText(_translate("SampleMain", "Clear"))
        self.actionSaveAs.setText(_translate("SampleMain", "Save as"))
        self.actionSaveAs1.setText(_translate("SampleMain", "Save As"))
        self.actionNew.setText(_translate("SampleMain", "New"))
        self.actionNew.setShortcut(_translate("SampleMain", "Ctrl+N"))
        self.actionSkill_Tool.setText(_translate("SampleMain", "Skill Tool"))
        self.actionSkill_Tool.setShortcut(_translate("SampleMain", "Alt+S"))
